sonar.projectKey=SONAR_PROJECT_KEY
sonar.projectName=news-activities-for-hackers
sonar.host.url=https://sonarcloud.io
sonar.organization=SONAR_ORGANIZATION_KEY
sonar.sources=src
sonar.language=tsx
sonar.exclusions=**/node_modules/**,**/*.test.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.login=SONAR_TOKEN